export type Rarity = "COMMON" | "RARE" | "EPIC" | "LEGENDARY";

export interface BadgeDef {
  id: string;
  name: string;
  emoji: string;
  desc: string;
  flavour: string;
  rarity: Rarity;
  rarityColor: string;
  gradTop: string;
  gradBot: string;
  rimColor: string;
  matchFn: (earnedBadges: string[], solvedCases: string[], level: number, streak: number) => boolean;
}

const r: Record<Rarity, string> = {
  COMMON: "#7A85A3",
  RARE: "#4A7EE8",
  EPIC: "#9B59B6",
  LEGENDARY: "#D4962A",
};

export const BADGE_DEFS: BadgeDef[] = [
  {
    id: "first_blood",
    name: "First Blood",
    emoji: "🩸",
    desc: "Solve your very first case",
    flavour: "The investigation has begun. Heaven help the suspects.",
    rarity: "COMMON",
    rarityColor: r.COMMON,
    gradTop: "#3D0010",
    gradBot: "#1A0008",
    rimColor: "#8B1A2C",
    matchFn: (_b, solved) => solved.length >= 1,
  },
  {
    id: "brotherhood_broken",
    name: "Brotherhood Broken",
    emoji: "⚔️",
    desc: "Solve The First Murder",
    flavour: "The first detective case in all of human history. No pressure.",
    rarity: "COMMON",
    rarityColor: r.COMMON,
    gradTop: "#1A1010",
    gradBot: "#0A0808",
    rimColor: "#8B3A3A",
    matchFn: (_b, solved) => solved.includes("001"),
  },
  {
    id: "deception_master",
    name: "Deception Master",
    emoji: "🫘",
    desc: "Solve The Stolen Birthright",
    flavour: "Stew for a birthright. The worst trade deal in biblical history.",
    rarity: "COMMON",
    rarityColor: r.COMMON,
    gradTop: "#101A10",
    gradBot: "#080A08",
    rimColor: "#3A8B3A",
    matchFn: (_b, solved) => solved.includes("002"),
  },
  {
    id: "coat_of_colors",
    name: "Coat of Colors",
    emoji: "🌈",
    desc: "Solve The Betrayal in Egypt",
    flavour: "From pit to palace. Joseph took the scenic route.",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#1A1530",
    gradBot: "#0A0818",
    rimColor: "#5A48C8",
    matchFn: (_b, solved) => solved.includes("003"),
  },
  {
    id: "broken_chains",
    name: "Broken Chains",
    emoji: "⛓️",
    desc: "Solve The Samson Betrayal",
    flavour: "The strongest man who ever lived was undone by a haircut.",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#102030",
    gradBot: "#081018",
    rimColor: "#3A6890",
    matchFn: (_b, solved) => solved.includes("004"),
  },
  {
    id: "wisdoms_crown",
    name: "Wisdom's Crown",
    emoji: "👑",
    desc: "Solve The Judgment of Solomon",
    flavour: "You think like a king. Or at least like someone who asked for wisdom.",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#251A30",
    gradBot: "#140A18",
    rimColor: "#8040A8",
    matchFn: (_b, solved) => solved.includes("005"),
  },
  {
    id: "gethsemane_witness",
    name: "Gethsemane Witness",
    emoji: "🕊️",
    desc: "Solve The Betrayal in the Garden",
    flavour: "You witnessed the darkest and brightest moment in history.",
    rarity: "EPIC",
    rarityColor: r.EPIC,
    gradTop: "#151525",
    gradBot: "#0A0A18",
    rimColor: "#6060B8",
    matchFn: (_b, solved) => solved.includes("006"),
  },
  {
    id: "truth_seeker",
    name: "Truth Seeker",
    emoji: "🔍",
    desc: "Complete all 6 cases",
    flavour: "All six cases solved. The ancient world holds no secrets from you.",
    rarity: "EPIC",
    rarityColor: r.EPIC,
    gradTop: "#1A1028",
    gradBot: "#0A0815",
    rimColor: "#7840B8",
    matchFn: (_b, solved) => solved.length >= 6,
  },
  {
    id: "on_fire",
    name: "On Fire",
    emoji: "🔥",
    desc: "Maintain a 3-day streak",
    flavour: "Three days in a row. Detective work is becoming a habit. (We're not complaining.)",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#2A1000",
    gradBot: "#150800",
    rimColor: "#C86820",
    matchFn: (_b, _s, _l, streak) => streak >= 3,
  },
  {
    id: "scripture_keeper",
    name: "Scripture Keeper",
    emoji: "📜",
    desc: "Reach Level 5",
    flavour: "Level 5. Your seminary professors are concerned.",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#201A00",
    gradBot: "#100D00",
    rimColor: "#907800",
    matchFn: (_b, _s, level) => level >= 5,
  },
  {
    id: "just_judge",
    name: "Just Judge",
    emoji: "⚖️",
    desc: "Solve 3 cases correctly",
    flavour: "Justice scales perfectly balanced. Like all things should be.",
    rarity: "EPIC",
    rarityColor: r.EPIC,
    gradTop: "#1E0A30",
    gradBot: "#0F0518",
    rimColor: "#9020C0",
    matchFn: (_b, solved) => solved.length >= 3,
  },
  {
    id: "master_sleuth",
    name: "Master Sleuth",
    emoji: "🕵️",
    desc: "Reach Level 10",
    flavour: "Level 10 achieved. At this rate you'll be writing the commentary.",
    rarity: "LEGENDARY",
    rarityColor: r.LEGENDARY,
    gradTop: "#251500",
    gradBot: "#150B00",
    rimColor: "#D4962A",
    matchFn: (_b, _s, level) => level >= 10,
  },
];
