import type { BadgeIconId } from "@/components/ui/SvgIcons";

export type Rarity = "COMMON" | "RARE" | "EPIC" | "LEGENDARY";

export interface BadgeDef {
  id: string;
  name: string;
  svgIcon: BadgeIconId;
  desc: string;
  flavour: string;
  rarity: Rarity;
  rarityColor: string;
  gradTop: string;
  gradBot: string;
  rimColor: string;
  matchFn: (earnedBadges: string[], solvedCases: string[], level: number, streak: number) => boolean;
}

const r: Record<Rarity, string> = {
  COMMON: "#7A85A3",
  RARE: "#4A7EE8",
  EPIC: "#9B59B6",
  LEGENDARY: "#D4962A",
};

export const BADGE_DEFS: BadgeDef[] = [
  {
    id: "first_blood",
    name: "First Blood",
    svgIcon: "first_blood",
    desc: "Solve your very first case",
    flavour: "The investigation has begun. Heaven help the suspects.",
    rarity: "COMMON",
    rarityColor: r.COMMON,
    gradTop: "#2A0008",
    gradBot: "#150004",
    rimColor: "#8B1A2C",
    matchFn: (_b, solved) => solved.length >= 1,
  },
  {
    id: "brotherhood_broken",
    name: "Brotherhood Broken",
    svgIcon: "brotherhood_broken",
    desc: "Solve The First Murder",
    flavour: "The first detective case in all of human history. No pressure.",
    rarity: "COMMON",
    rarityColor: r.COMMON,
    gradTop: "#1A1010",
    gradBot: "#0A0808",
    rimColor: "#8B3A3A",
    matchFn: (_b, solved) => solved.includes("001"),
  },
  {
    id: "deception_master",
    name: "Deception Master",
    svgIcon: "deception_master",
    desc: "Solve The Stolen Birthright",
    flavour: "Stew for a birthright. The worst trade deal in biblical history.",
    rarity: "COMMON",
    rarityColor: r.COMMON,
    gradTop: "#081408",
    gradBot: "#040A04",
    rimColor: "#3A8B3A",
    matchFn: (_b, solved) => solved.includes("002"),
  },
  {
    id: "coat_of_colors",
    name: "Coat of Colors",
    svgIcon: "coat_of_colors",
    desc: "Solve The Betrayal in Egypt",
    flavour: "From pit to palace. Joseph took the scenic route.",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#0A0820",
    gradBot: "#050410",
    rimColor: "#5A48C8",
    matchFn: (_b, solved) => solved.includes("003"),
  },
  {
    id: "broken_chains",
    name: "Broken Chains",
    svgIcon: "broken_chains",
    desc: "Solve The Samson Betrayal",
    flavour: "The strongest man who ever lived was undone by a haircut.",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#061020",
    gradBot: "#030810",
    rimColor: "#3A6890",
    matchFn: (_b, solved) => solved.includes("004"),
  },
  {
    id: "wisdoms_crown",
    name: "Wisdom's Crown",
    svgIcon: "wisdoms_crown",
    desc: "Solve The Judgment of Solomon",
    flavour: "You think like a king. Or at least like someone who asked for wisdom.",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#1A1000",
    gradBot: "#0D0800",
    rimColor: "#8040A8",
    matchFn: (_b, solved) => solved.includes("005"),
  },
  {
    id: "gethsemane_witness",
    name: "Gethsemane Witness",
    svgIcon: "gethsemane_witness",
    desc: "Solve The Betrayal in the Garden",
    flavour: "You witnessed the darkest and brightest moment in history.",
    rarity: "EPIC",
    rarityColor: r.EPIC,
    gradTop: "#080818",
    gradBot: "#04040C",
    rimColor: "#6060B8",
    matchFn: (_b, solved) => solved.includes("006"),
  },
  {
    id: "truth_seeker",
    name: "Truth Seeker",
    svgIcon: "truth_seeker",
    desc: "Complete all 6 cases",
    flavour: "All six cases solved. The ancient world holds no secrets from you.",
    rarity: "EPIC",
    rarityColor: r.EPIC,
    gradTop: "#0E0618",
    gradBot: "#07030C",
    rimColor: "#7840B8",
    matchFn: (_b, solved) => solved.length >= 6,
  },
  {
    id: "on_fire",
    name: "On Fire",
    svgIcon: "on_fire",
    desc: "Maintain a 3-day streak",
    flavour: "Three days in a row. Detective work is becoming a habit. (We're not complaining.)",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#1E0A00",
    gradBot: "#0F0500",
    rimColor: "#C86820",
    matchFn: (_b, _s, _l, streak) => streak >= 3,
  },
  {
    id: "scripture_keeper",
    name: "Scripture Keeper",
    svgIcon: "scripture_keeper",
    desc: "Reach Level 5",
    flavour: "Level 5. Your seminary professors are concerned.",
    rarity: "RARE",
    rarityColor: r.RARE,
    gradTop: "#181200",
    gradBot: "#0C0900",
    rimColor: "#907800",
    matchFn: (_b, _s, level) => level >= 5,
  },
  {
    id: "just_judge",
    name: "Just Judge",
    svgIcon: "just_judge",
    desc: "Solve 3 cases correctly",
    flavour: "Justice scales perfectly balanced. Like all things should be.",
    rarity: "EPIC",
    rarityColor: r.EPIC,
    gradTop: "#120520",
    gradBot: "#090310",
    rimColor: "#9020C0",
    matchFn: (_b, solved) => solved.length >= 3,
  },
  {
    id: "master_sleuth",
    name: "Master Sleuth",
    svgIcon: "master_sleuth",
    desc: "Reach Level 10",
    flavour: "Level 10 achieved. At this rate you'll be writing the commentary.",
    rarity: "LEGENDARY",
    rarityColor: r.LEGENDARY,
    gradTop: "#1A0E00",
    gradBot: "#0D0700",
    rimColor: "#D4962A",
    matchFn: (_b, _s, level) => level >= 10,
  },
];
